### ISSUE TITLE
PING and REQ do not work together

### ISSUE THREAD

**Issue by sparkpunkd** [nrkno/tv-automation-casparcg-server#26]
Should they?

```
PING
PONG
REQ 1234 PING
RES 1234 400 ERROR
REQ 1234 PING
```

**Comment by Julusian** [comment]
No, this is expected. PING had to be done much much earlier inside the AMCP parsing code in caspar so that it could be left out of the logs. This means it is before the REQ/RES handling, so they will not work together.
To allow for similar behaviour, PING has an id parameter, which will get echoed back in the pong

**Comment by sparkpunkd** [comment]
Thanks for the pointer! 

The real problem here is that PING, its behavior and some other new commands are currently undocumented. I'm going to prepare and propose a documentation update for AMCP.
