### ISSUE TITLE
Server Crashing with Remove 1 File

### ISSUE THREAD

**Issue by sirfnomi** [nrkno/tv-automation-casparcg-server#45]
As mentioned in subject server 2.1.11 is crashing with Remove 1 File command

Steps to reproduce:

1. add 1 File "abc.mov"
2. Remove 1 File

**Comment by sirfnomi** [comment]
But server 2.3 isn't crashing with it

**Comment by sparkpunkd** [comment]
Yes. And we have done a line-by-line comparison of the code to look at the differences between the versions and not found an obvious reason. Not to say we didn't miss something?

**Comment by Julusian** [comment]
2.2 and 2.3 use a newer compiler (vs2017/vs2019 vs vs2015), which is what we think the proper fix for this issue would be.
But we havent been able to justify the time (or risk) of using a newer compiler for an issue that has a simple workaround.

**Comment by sirfnomi** [comment]
Ohh so it means we can't use record feature right now. I think for recording we should use Server 2.0.8

**Comment by sirfnomi** [comment]
Hi, 
Please fix this issue. 
Also, updated cef version is in plan ?

Thanks

**Comment by nytamin** [comment]
Hi @sirfnomi!

Due to that NRK isn't currently using the record-feature, will probably not spend resources for this fix ourselves. If you find a solution however, we would be happy to accept a Pull Request with the fix!

Regarding updating CEF; I can't give you an estimate as it has turned out the CEF update turned out to be a larger task.
